name: Metrics
on:
  schedule: [{cron: "0 17 * * *"}]
  workflow_dispatch:
  push: {branches: ["master", "main"]}

jobs:
  github-metrics:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: lowlighter/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          
          # --- Layout Utama ---
          user: ${{ github.repository_owner }}
          template: classic
          config_display: large
          config_timezone: Asia/Jakarta
          base: header, activity, community, repositories, metadata
          
          # --- 1. Bahasa Pemrograman ---
          plugin_languages: yes
          plugin_languages_ignored: html, css
          plugin_languages_limit: 8
          
          # --- 2. Kalender 3D ---
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year

          # --- 3. Ikon Teknologi (Wajib Star repo dulu!) ---
          plugin_topics: yes
          plugin_topics_limit: 15
          plugin_topics_mode: icons
          
          # --- 4. Penghargaan (Diperbaiki) ---
          plugin_achievements: yes
          plugin_achievements_display: compact
          # Ubah dari X ke C supaya achievement dasar muncul
          plugin_achievements_threshold: C 
          plugin_achievements_secrets: yes
